### ISSUE TITLE
Different  prefix does not work

### ISSUE THREAD

**Issue by jcamachott** [jgulledge19/CMPGenerator#9]
I used a table called jta_holidays. Prefix I entered as jta_ and followed everything else as in the instructions. Created a test snippet as in https://rtfm.modx.com/extras/revo/cmpgenerator/cmpgenerator.5-minute-example and it did not work. In the error log, it was looking for modx_holidays.

So the only workaround was to rename the table - then it all worked perfectly.

**Comment by jgulledge19** [comment]
Also when you add your package you have to state the prefix: https://rtfm.modx.com/xpdo/2.x/class-reference/xpdo/xpdo.addpackage

**Comment by jcamachott** [comment]
Thanks!
